[package]
name = "ssg"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
name = "ssg"
path = "src/lib/mod.rs"

[[bin]]
name = "ssg"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = "full"
incremental = true
codegen-units = 8

[profile.release]
opt-level = 3
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
strip = "symbols"

[dependencies]
blake3 = { version = "1.8.7", default-features = false, features = ["std"] }
cap-std = { version = "4.0.3", default-features = false }
color-eyre = { version = "0.6.5", default-features = false }
rusqlite = { version = "0.40.2", default-features = false }
rustix = { version = "1.1.5", default-features = false, features = ["fs", "std"] }
thiserror = { version = "2.0.21", default-features = false, features = [
  # Needed for errors to implement `std::error::Error`
  "std"
]}
walkdir = { version = "2.5.0", default-features = false }

[dev-dependencies]
proptest = "1.11.0"
proptest-derive = "0.8.0"
tempdir = "0.3.7"
